### ISSUE TITLE
Nautilus 45 headerbar issue

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/Colloid-gtk-theme#132]
The headerbar of the place sidebar has 6px gap with the toolbar of the main window of Nautilus. See the following image.

![1](https://github.com/vinceliuice/Colloid-gtk-theme/assets/1250269/842f7eca-1233-4fd3-a4a0-33d0164e1081)

After browsing the source code of libadwaita, I found this is caused by the CSS style:

```css
toolbarview .collapse-spacing {
  padding-top: 3px;
  padding-bottom: 3px;
}
```

If you set these paddings as 0, the issue will be resolved.
