### ISSUE TITLE
Colloid issue with shell + dash to dock css issue( missing drop shadow,border..)

### ISSUE THREAD

**Issue by buinguyenhoangtho** [vinceliuice/Colloid-gtk-theme#26]
Hi author ! 
I want to report, look like is css issue with dash to dock and dark colloid theme
![missing](https://i.imgur.com/y1jRbqc.png)
You can see. The menu don't have drop shadow when using with gnome-shell

**Comment by buinguyenhoangtho** [comment]
Nvm i just find out the way. 
To add border. Go to `colorlloid-dark/gnome-shell/gnome-shell.css`
Look for `popup-menu .popup-menu-content `  class . Add `border: 1px solid #212121;
  font-weight: normal;`
```css
.popup-menu .popup-menu-content {
  padding: 6px 0 !important;
  background-color: #2c2c2c;
  border-radius: 12px;
  margin: 0;
  /* dropshadow */
  border: 1px solid #212121;
  font-weight: normal;
}
```
Result: 
![Result](https://i.imgur.com/ThjhSMN.png)
