### ISSUE TITLE
Font selection in GNOME Text Editor is broken

### ISSUE THREAD

**Issue by kodemeister** [vinceliuice/Colloid-gtk-theme#87]
Hi @vinceliuice ,

Thank you for your hard work! The theme looks really gorgeous!

After installing the theme with `--libadwaita` I cannot change font in [GNOME Text Editor](https://apps.gnome.org/app/org.gnome.TextEditor) anymore. The editor always uses **Monospace 14** regardless of what font I selected in the app settings. The theme previews also look broken as shown below:

![gnome-text-editor](https://user-images.githubusercontent.com/1043953/200738428-912a37a7-03d3-4615-a992-a39d9b1a6553.png)

I found two offending CSS rules that seem to cause this bug:

1. `.monospace` in `_common-4.0.scss`. It always resets editor font family to Monospace.
```css
.monospace { font-family: monospace; }
```

2. `.sourceview` in `_gnome-4.0.scss`. Despite the "Calculator" comment above, the rule is too general. It actually resets font size to 14 pt in all editing apps based on gtksourceview.
```css
.sourceview {
  padding: 0 12px 8px 0;
  font-size: 1.4em;
  border-top: 1px solid $border;
}
```

Commenting out both rules fixed the issue for me.

Can we make these rules a bit more specific so that they won't affect the Text Editor app?
